### PR TITLE
Revert "intf refactoring - logic, code conventions, var scope and styling"

### PR DESCRIPTION
**Pull request by ophirhan**
Reverts ophirhan/cnsr-vlc-viewer-addon#28

### CODE REVIEW

**Comment by ishayhil** [comment]
@ophirhan you want me to reopen #28 so you can comment on the problematic line?

**Comment by ophirhan** [comment]
Haven't found it yet, can you make a pull request to a branch other than main?

**Comment by ishayhil** [comment]
@ophirhan I don't have access to create new branches. Reopening PR and you can change the target branch as you have write repo permissions

**Comment by ophirhan** [comment]
Ok

**Pull request merged**
